name: Python application test with Github Actions using devcontainers

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and test inside Dev Container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            make install
            make lint
            make test
            make format
